version: "3.0"
services:
  backend:
    build:
      context: .
      dockerfile: dev.dockerfile
      cache_from:
        - redis:alpine
        - postgres:latest
        - mongo:latest
    container_name: sinarlog-backend
    image: sinarlog-app
    restart: always
    environment:
      - GO_ENV=TESTING
      # App Config
      - HOST=${HOST}
      - PORT=${PORT}
      - LOG_PATH=${LOG_PATH}
      - DEFAULT_ROWS_PER_PAGE=${DEFAULT_ROWS_PER_PAGE}
      # DB
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MAX_POOL_SIZE=${DB_MAX_POOL_SIZE}
      - DB_MAX_OPEN_CONN=${DB_MAX_OPEN_CONN}
      - DB_MAX_CONN_LIFETIME=${DB_MAX_CONN_LIFETIME}
      # Mongo
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_NAME=${MONGO_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_MAX_POOL_SIZE=${MONGO_MAX_POOL_SIZE}
      - MONGO_MAX_OPEN_CONN=${MONGO_MAX_OPEN_CONN}
      - MONGO_MAX_CONN_LIFETIME=${MONGO_MAX_CONN_LIFETIME}
      # Rate Limitting
      - RATER_LIMIT=${RATER_LIMIT}
      - BURST_LIMIT=${BURST_LIMIT}
      - RATER_EVALUATION_INTERVAL=${RATER_EVALUATION_INTERVAL}
      - RATER_DELETION_TIME=${RATER_DELETION_TIME}
      # Doorkeeper/Auth
      - DOORKEEPER_ISSUER=${DOORKEEPER_ISSUER}
      - DOORKEEPER_HASH_METHOD=${DOORKEEPER_HASH_METHOD}
      - DOORKEEPER_SIGNING_METHOD=${DOORKEEPER_SIGNING_METHOD}
      - DOORKEEPER_SIGN_SIZE=${DOORKEEPER_SIGN_SIZE}
      - DOORKEEPER_CERT_PRIVATE_PATH=${DOORKEEPER_CERT_PRIVATE_PATH}
      - DOORKEEPER_CERT_PUBLIC_PATH=${DOORKEEPER_CERT_PUBLIC_PATH}
      - DOORKEEPER_ACCESS_TOKEN_DURATION=${DOORKEEPER_ACCESS_TOKEN_DURATION}
      - DOORKEEPER_REFRESH_TOKEN_DURATION=${DOORKEEPER_REFRESH_TOKEN_DURATION}
      - DOORKEEPER_OTP_EXPIRATION_DURATION=${DOORKEEPER_OTP_EXPIRATION_DURATION}
      - DOORKEEPER_OTP_SECRET_LENGTH=${DOORKEEPER_OTP_SECRET_LENGTH}
      # Mailer
      - MAILER_SENDER_ADDRESS=${MAILER_SENDER_ADDRESS}
      - MAILER_SENDER_PASSWORD=${MAILER_SENDER_PASSWORD}
      # Redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_READ_TIMEOUT=${REDIS_READ_TIMEOUT}
      - REDIS_WRITE_TIMEOUT=${REDIS_WRITE_TIMEOUT}
      - REDIS_MIN_IDLE_CONN=${REDIS_MIN_IDLE_CONN}
      - REDIS_MAX_IDLE_CONN=${REDIS_MAX_IDLE_CONN}
      - REDIS_MAX_IDLE_TIME=${REDIS_MAX_IDLE_TIME}
      # Firebase
      - FIREBASE_BUCKET_SERVICE_ACCOUNT_PATH=${FIREBASE_BUCKET_SERVICE_ACCOUNT_PATH}
      - FIREBASE_BUCKET_NAME=${FIREBASE_BUCKET_NAME}
      # Google Config
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_KEY_PATH=${GOOGLE_KEY_PATH}
    ports:
      - ${PORT}:${PORT}
    networks:
      - sinarlog-network
    depends_on:
      - pg
      - redis
      - mongo

  pg:
    image: postgres:latest
    container_name: sinarlog_pg
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - sinarlog-pg-data:/var/lib/postgresql/data
    networks:
      - sinarlog-network
    depends_on:
      - redis
      - mongo

  redis:
    image: redis:alpine
    container_name: sinarlog_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always
    volumes:
      - sinarlog-redis-data:/data
    networks:
      - sinarlog-network

  mongo:
    image: mongo:latest
    container_name: sinarlog_mongo
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - sinarlog-mongo-data:/data
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_NAME}
    networks:
      - sinarlog-network

volumes:
  sinarlog-pg-data:
  sinarlog-redis-data:
  sinarlog-mongo-data:
networks:
  sinarlog-network:
